/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.szydlowski.nucleusweb.server;

/**
 *
 * @author Dominik
 */
public class HtmlStyle {
     
     public static final String ERROR404_DATA="<h1>401 UNAUTHORIZED. Authentication required.</h1><b><br/>Sorry, you are not allowed to access this page.</b><br/>";
     public static final String ERROR404 =  new StringBuilder().append("HTTP/1.1 401 UNAUTHORIZED\r\n")
             .append("Content-Length: ").append(ERROR404_DATA.length()).append("\r\n")
             .append("Content-Type: text/html\r\n\r\n" )
             .append(ERROR404_DATA).toString();
           
    
      public static final String LINKSTYLE = new StringBuilder().append("<style>\n" )
            .append("a:link { color: #696; text-decoration: none; background-color: transparent }\n" )
            .append("a:visited { color: red; text-decoration: none; background-color: transparent }\n" )
            .append("a:hover { color: #c93; text-decoration: underline; background-color: transparent }\n" )
            .append("a:active { color: #900; text-decoration: underline; background-color: transparent }\n" )
            .append("</style>").toString();
      
        
       public static final String TOPNAV_STYLE = new StringBuilder().append("\n .topnav {\n" )
                .append("  background-color: #333;\n" )
                .append("  overflow: hidden;\n" )
                .append("}\n" )
                .append("\n" )
                .append("/* Style the links inside the navigation bar */\n" )
                .append(".topnav a {\n" )
                .append("  float: left;\n" )
                .append("  color: #f2f2f2;\n" )
                .append("  text-align: center;\n" )
                .append("  padding: 14px 16px;\n" )
                .append("  text-decoration: none;\n" )
                .append("  font-size: 17px;\n" )
                .append("}\n" )
                .append("\n" )
                .append("/* Change the color of links on hover */\n" )
                .append(".topnav a:hover {\n" )
                .append("  background-color: #ddd;\n" )
                .append("  color: black;\n" )
                .append("}\n" )
                .append("\n" )
                .append("/* Add a color to the active/current link */\n" )
                .append(".topnav a.active {\n" )
                .append("  background-color: #4CAF50;\n" )
                .append("  color: white;\n" )
                .append("}").toString();

       public static final String CELL_COMMENT_STYLE = new StringBuilder().append("\n .CellWithComment{\n" )
                .append("  position:relative;\n" )
                .append("}\n" )
                .append("\n" )
                .append(".CellComment{\n" )
                .append("  display:none;\n" )
                .append("  position:absolute; \n" )
                .append("  z-index:100;\n" )
                .append("  border:1px;\n" )
                .append("  background-color:white;\n" )
                .append("  border-style:solid;\n" )
                .append("  border-width:1px;\n" )
                .append("  border-color:red;\n" )
                .append("  padding:3px;\n" )
                .append("  color:red; \n" )
                .append("  top:20px; \n" )
                .append("  left:20px;\n" )
                .append("}\n" )
                .append("\n" )
                .append(".CellWithComment:hover span.CellComment{\n" )
                .append("  display:block;\n" )
                .append("}").toString();
       
       public static final String TABLE_STYLE = new StringBuilder().append("\n  body {font-family: Arial;}\n" )
            .append("/* Style the tab */\n" )
            .append(".tab {\n" )
            .append("  overflow: hidden;\n" )
            .append("  border: 1px solid #ccc;\n" )
            .append("  background-color: #f1f1f1;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Style the buttons inside the tab */\n" )
            .append(".tab button {\n" )
            .append("  background-color: inherit;\n" )
            .append("  float: left;\n" )
            .append("  border: none;\n" )
            .append("  outline: none;\n" )
            .append("  cursor: pointer;\n" )
            .append("  padding: 14px 16px;\n" )
            .append("  transition: 0.3s;\n" )
            .append("  font-size: 17px;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Change background color of buttons on hover */\n" )
            .append(".tab button:hover {\n" )
            .append("  background-color: #ddd;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Create an active/current tablink class */\n" )
            .append(".tab button.active {\n" )
            .append("  background-color: #4CAF50;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Style the tab content */\n" )
            .append(".tabcontent {\n" )
            .append("  display: none;\n" )
            .append("  padding: 6px 12px;\n" )
            .append("  -webkit-animation: fadeEffect 1s;\n" )
            .append("  animation: fadeEffect 1s;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Fade in tabs */\n" )
            .append("@-webkit-keyframes fadeEffect {\n" )
            .append("  from {opacity: 0;}\n" )
            .append("  to {opacity: 1;}\n" )
            .append("}\n" )
            .append("\n" )
            .append("@keyframes fadeEffect {\n" )
            .append("  from {opacity: 0;}\n" )
            .append("  to {opacity: 1;}\n" )
            .append("}\n" )
            .append("table {\n" )
            .append("  font-family: arial, sans-serif;\n" )
            .append("  border-collapse: collapse;\n" )
            .append("  width: 100%;\n" )
            .append("}\n" )
            .append("\n" )
            .append("th {\n" )
            .append("  border: 1px solid #dddddd;\n" )
            .append("  text-align: left;\n" )
            .append("  background-color: #008CBA; \n")
            .append("  color: white;\n")
            .append("  padding: 8px;\n" )
            .append("}\n" )
            .append("td{\n" )
            .append("  border: 1px solid #dddddd;\n" )
            .append("  text-align: left;\n" )
            .append("  padding: 8px;\n" )
            .append("}\n" )
            .append("\n" )
            .append("tr:nth-child(even) {\n" )
            .append("  background-color: #cccccc;\n" )
            .append("}")
            .append("tr:nth-child(odd) {\n" )
            .append("  background-color: #f2f2f2;\n" )
            .append("}")
            .append("tr:hover {background-color:#4CAF50;}") //podswietlanie
            .append(".button-exc {\n")
            .append("  background-color: #008CBA; \n")
            .append("  border: none;\n")
            .append("  color: white;\n")
            .append("  padding: 3px 8px;\n")
            .append("  text-align: center;\n")
            .append("  text-decoration: none;\n")
            .append("  display: inline-block;\n")
            .append("  font-size: 16px;\n")
            .append("  margin: 2px 2px;\n")
            .append("  cursor: pointer;\n")
            .append("}")
            .append("table.scroll {\n")
            .append("    width: 1400px; /* 140px * 3 column + 16px scrollbar width */\n" )
            .append("    border-spacing: 0;\n" )
            .append("    border: 1px solid black;\n" )
            .append("}\n" )
            .append("\n" )
            .append("table.scroll tbody,\n" )
            .append("table.scroll thead tr { display: block; }\n" )
            .append("\n" )
            .append("table.scroll tbody {\n" )
            .append("    max-height: 400px;\n" )
            .append("    overflow-y: auto;\n" )
            .append("    overflow-x: hidden;\n" )
            .append("}\n" )
            .append("\n" )
            .append("table.scroll tbody td,\n" )
            .append("table.scroll thead th {\n" )
            .append("    width: 200px;\n" )
            .append("    border-right: 1px solid black;\n" )
            .append("}\n" )
            .append("\n" )
            .append("thead tr th { \n" )
            .append("    height: 30px;\n" )
            .append("    line-height: 30px;\n" )
            .append("    position: sticky;\n" )
            .append("    top: 0;")
            .append("}\n" )
            .append("\n" )
            .append("tbody { border-top: 2px solid black; }\n" )
            .append("\n" )
            .append("tbody td:last-child, thead th:last-child {\n" )
            .append("    border-right: none !important;\n" )
            .append("}")   
            .toString();
       
       public static final String FIND_INPUT_STYLE = new StringBuilder().append("\n   .searchInput {\n")
            .append("\t  background-position: 10px 10px;\n")
            .append("\t  background-repeat: no-repeat;\n")
            .append("\t  width: 1400px\n;")
            .append("\t  font-size: 16px;\n")
            .append("\t  padding: 12px 20px 12px 40px;\n")
            .append("\t  border: 1px solid #ddd;\n")
            .append("\t  margin-bottom: 12px;\n")
            .append("\t     }").toString();
       
                 
}
